# Generated by Django 5.0.6 on 2024-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments_user_alter_comments_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='category',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_listings', to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watched_listings',
            field=models.ManyToManyField(blank=True, related_name='watched_users', to='auctions.auction_listings'),
        ),
    ]
