# Generated by Django 5.0.6 on 2024-06-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_listings_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_Listings',
            new_name='Auction_Listing',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
